# Generated by Django 4.2.2 on 2023-06-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/product_img')),
                ('title', models.CharField(max_length=100, verbose_name='Product Name')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('date_field', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
