# Generated by Django 4.2.2 on 2023-06-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
